---
# tasks file for install-db
# These task installs and enables apache on webservers
- name: ensure mysql is installed
  yum: name={{ item }} state=present
  with_items:
   - mysql
   - mariadb-server
   - MySQL-python
- name: ensure mysql is running
  service: name=mariadb state=running enabled=yes
- name: create application database
  mysql_db: name={{ item }} state=present
  with_items:
   - ansible_db01
   - ansible_db02
- name: create application user
  mysql_user: name={{ dbuser }} password={{ dbpassword }} priv=*.*:ALL state=present
